<?php

/**
 * @file
 * Contains simplenews_import.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function simplenews_import_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the simplenews_import module.
    case 'help.page.simplenews_import':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}
